# Exported from Render on 2024-05-26T13:31:14Z
databases:
  - name: fyp-crowdfunding-database
    databaseName: fyp_crowdfunding_database
    user: fyp_crowdfunding_database_user
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "15"
services:
  - type: web
    name: fyp-crowdfunding
    runtime: docker
    repo: https://github.com/ludndev/fyp-crowdfunding
    plan: free
    envVars:
      - key: DB_CONNECTION
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: fyp-crowdfunding-database
          property: connectionString
      - key: APP_NAME
        sync: false
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        sync: false
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: "1"
